{{- if .Values.cnpg }}
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ template "tranquil.fullname" . }}-db
spec:
  bootstrap:
    initdb:
      database: {{ template "tranquil.fullname" . }}
      owner: {{ template "tranquil.fullname" . }}
  instances: {{ .Values.cnpg.instances }}
  storage:
    size: {{ .Values.cnpg.size }}
{{- end }}

