---
{{- $threads := 1 }}
{{- if .Values.resources.limits.cpu }}
  {{- if typeIs "string" .Values.resources.limits.cpu }}
    {{- $trimmed := trimSuffix "m" .Values.resources.limits.cpu }}
    {{- $value := ternary (float64 $trimmed | ceil | mul 1000) $trimmed (contains "." $trimmed) | int64 }}
    {{- if eq (mod $value 1000) 0 }}
      {{- $threads = div $value 1000 }}
    {{- else }}
      {{- $threads = add1 (div $value 1000) }}
    {{- end }}
  {{- else }}
    {{- $threads = .Values.resources.limits.cpu }}
  {{- end }}
{{- end }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ template "tranquil.fullname" . }}
  labels:
    {{- include "tranquil.labels" . | nindent 4 }}
    app.kubernetes.io/component: tranquil
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: 2
  selector:
    matchLabels:
      {{- include "tranquil.labels" . | nindent 6 }}
      app.kubernetes.io/component: tranquil
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-app
    spec:
      containers:
        - name: {{ template "tranquil.fullname" . }}-container
          image: "atcr.io/tranquil.farm/tranquil-pds:{{ tpl .Values.image.tag . }}"
          ports:
            - name: http
              containerPort: 8080
          env:
          {{- if or (.Values.env) (.Values.envRaw) (.Values.envFromSecret) }}
          {{- range $key, $val := .Values.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
          {{- end }}
          {{- if .Values.envRaw }}
            {{- with .Values.envRaw }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
          {{- range $key, $val := .Values.envFromSecret }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ (split "/" $val)._0 }}
                  key: {{ (split "/" $val)._1 }}
          {{- end }}
          {{- end }}
          {{- if .Values.cnpg }}
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ template "tranquil.fullname" . }}-db-app # CNPG secret
                  key: uri
          {{- else }}
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.existingSecret.name }} # CNPG secret
                  key: {{ .Values.postgres.existingSecret.key }}
          {{- end }}
          envFrom:
          - configMapRef:
              name: {{ .Release.Name }}-configmap
          - secretRef:
              name: {{ .Release.Name }}-secret
      imagePullSecrets:
        - name: {{ .Release.Name }}-registry-key

